from datetime import datetime
from django.test import TestCase
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
class Hosttest(TestCase):
    
    def setUp(self):
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(10)
        self.live_server_url = 'http://127.0.0.1:8000/'

    def tearDown(self):
        self.driver.quit()
        
    def test_01_login_page(self):
        driver = self.driver
        driver.get(self.live_server_url)
        driver.maximize_window()
        time.sleep(1)
        login=driver.find_element(By.CSS_SELECTOR,"a[href='/accounts/login/']")
        login.click()
        time.sleep(2)
        email=driver.find_element(By.CSS_SELECTOR,"input[type='email'][name='email']")
        email.send_keys("josephjames2024@mca.ajce.in")
        time.sleep(2)
        password=driver.find_element(By.CSS_SELECTOR,"input[type='password'][name='password']")
        password.send_keys("12043#BNbg")
        time.sleep(1)
        submitc=driver.find_element(By.CSS_SELECTOR,"button.btn.btn-primary.btn-block.fa-lg.gradient-custom-2.mb-3[type='submit']")
        submitc.click()
        time.sleep(2)
        print("login successfully")
        case=driver.find_element(By.CSS_SELECTOR,"a[href='/enter_client_email/']")
        case.click()
        time.sleep(1)
        add=driver.find_element(By.CSS_SELECTOR,"input[type='email'][name='client_email']")
        add.send_keys("sample1@gmail.com")
        time.sleep(2)
        submitcaseem=driver.find_element(By.CSS_SELECTOR,"button.btn.btn-warning[type='submit']")
        submitcaseem.click()
        time.sleep(2)
        print("Client Email entered Successfully for Case registration")
        adddetailsp=driver.find_element(By.CSS_SELECTOR,"input[type='text'][name='incident_place'][required]")
        adddetailsp.send_keys("Kochi")
        time.sleep(1)
        input_date = "2023-10-09"
        formatted_date = datetime.strptime(input_date, '%Y-%m-%d').strftime('%d-%m-%Y')
        adddetailsD = driver.find_element(By.CSS_SELECTOR, "input[type='date'][name='incident_date'][required]")
        adddetailsD.send_keys(formatted_date)
        time.sleep(1)
        adddetailsT = driver.find_element(By.CSS_SELECTOR, "input[type='time'][name='incident_time'][required]")
        adddetailsT.send_keys("15:10")
        time.sleep(1)
        adddetailsWN = driver.find_element(By.CSS_SELECTOR, "input[type='text'][name='witness_name'][required]")
        adddetailsWN.send_keys("Jesso Joeph")
        time.sleep(1)
        adddetailsWD = driver.find_element(By.CSS_SELECTOR, "textarea[name='witness_details']")
        adddetailsWD.send_keys("Palarivatam")
        time.sleep(1)
        adddetailsID = driver.find_element(By.CSS_SELECTOR, "textarea[name='incident_description']")
        adddetailsID.send_keys("Car Accident")
        time.sleep(1)
        adddetailsCAN = driver.find_element(By.CSS_SELECTOR, "input[type='number'][name='client_adhar'][required]")
        adddetailsCAN.send_keys("456145614568")
        time.sleep(1)
        # Replace 'file_path' with the actual path to the file you want to upload
        file_path = 'C:/Users/josep/Downloads/WhatsApp Image 2023-09-11 at 11.57.00.jpg'
        adddetailsCAP = driver.find_element(By.CSS_SELECTOR, "input[type='file'][name='client_adhar_photo'][required]")
        adddetailsCAP.send_keys(file_path)
        time.sleep(1)
        submitcasedetails=driver.find_element(By.CSS_SELECTOR,"button.btn.btn-warning[type='submit']")
        submitcasedetails.click()
        time.sleep(2)
        print("Case registration successfully completed")
        gotolawyerdash=driver.find_element(By.CSS_SELECTOR,"a.go-to-home")
        gotolawyerdash.click()
        time.sleep(2)
        LISTcase=driver.find_element(By.CSS_SELECTOR,"a[href='/list_cases/'] h6")
        LISTcase.click()
        time.sleep(1)
        showdetails=driver.find_element(By.CSS_SELECTOR,"button.btn.btn-success[type='submit']")
        showdetails.click()
        time.sleep(2)
        showid=driver.find_element(By.CSS_SELECTOR,"a[href='#2a'][data-toggle='tab']")
        showid.click()
        time.sleep(2)
        gotolawyerdash1=driver.find_element(By.CSS_SELECTOR,"a[href='/accounts/login/']")
        gotolawyerdash1.click()
        time.sleep(2)
        leave=driver.find_element(By.CSS_SELECTOR,"a[href='/mark_holiday/']")
        leave.click()
        time.sleep(2)
        print("Enter Date to apply leave")
        input_dates = "2023-10-24"
        formatted_dates = datetime.strptime(input_dates, '%Y-%m-%d').strftime('%d-%m-%Y')
        w1 = driver.find_element(By.CSS_SELECTOR, 'input[type="date"][name="holiday_date"][id="holiday_date"][required]')
        w1.send_keys(formatted_dates)
        time.sleep(2)
        students2=driver.find_element(By.CSS_SELECTOR,'button.btn.btn-warning.text-white[type="submit"]')
        students2.click()
        time.sleep(3)
        print("Leave Applied")
        back=driver.find_element(By.CSS_SELECTOR,"a.active[href='/accounts/login/']")
        back.click()
        time.sleep(2)
        awork=driver.find_element(By.CSS_SELECTOR,"a[href='/assign_work/']")
        awork.click()
        time.sleep(2)
        print("Add details to Assign Work to student")
        wdec = driver.find_element(By.CSS_SELECTOR, "textarea[name='description']")
        wdec.send_keys("Case Study")
        time.sleep(1)
        input_dates = "2023-10-13"
        formatted_dates = datetime.strptime(input_dates, '%Y-%m-%d').strftime('%d-%m-%Y')
        wd = driver.find_element(By.CSS_SELECTOR, "input[type='date'][name='deadline_date']")
        wd.send_keys(formatted_dates)
        time.sleep(1)
        s=driver.find_element(By.CSS_SELECTOR,"select[name='student_id'][required] option")
        s.click()
        time.sleep(2)
        students=driver.find_element(By.CSS_SELECTOR,"option[value='7']")
        students.click()
        time.sleep(2)
        st=driver.find_element(By.CSS_SELECTOR,"select#case_id[name='case_id']")
        st.click()
        time.sleep(2)
        caseid=driver.find_element(By.CSS_SELECTOR,"option[value='3']")
        caseid.click()
        time.sleep(2)
        subwo=driver.find_element(By.CSS_SELECTOR,"button.btn.btn-warning[type='submit']")
        subwo.click()
        time.sleep(2)
        print("Work Assigned")
        lo=driver.find_element(By.CSS_SELECTOR,"a[href='#'] > i.ti-angle-down")
        lo.click()
        time.sleep(2)
        lo1=driver.find_element(By.CSS_SELECTOR,"a[href='/logout/'  ]")
        lo1.click()
        time.sleep(2)
        print("Logout Successfull")
        emails=driver.find_element(By.CSS_SELECTOR,"input[type='email'][name='email']")
        emails.send_keys("donbenny2024@mca.ajce.in")
        time.sleep(2)
        passwords=driver.find_element(By.CSS_SELECTOR,"input[type='password'][name='password']")
        passwords.send_keys("12043#BNbg")
        time.sleep(1)
        submitcs=driver.find_element(By.CSS_SELECTOR,"button.btn.btn-primary.btn-block.fa-lg.gradient-custom-2.mb-3[type='submit']")
        submitcs.click()
        time.sleep(2) 
        mywork=driver.find_element(By.CSS_SELECTOR,"a[href='/work-assignments/'] > h6[style='padding: 0; margin: 0;']")
        mywork.click()
        time.sleep(2)
        gotodash=driver.find_element(By.CSS_SELECTOR,"a[href='/accounts/login/']")
        gotodash.click()
        time.sleep(2)
        logotst=driver.find_element(By.CSS_SELECTOR,"a[href='#'] > i.ti-angle-down")
        logotst.click()
        time.sleep(2)
        logotstl=driver.find_element(By.CSS_SELECTOR,"ul.submenu li a[href='/logout/']")
        logotstl.click()
        time.sleep(2)
        print("Logout Successfull")
        print("Test Completed Successfully")

        
        
        
       

    # Add more test methods as needed

if __name__ == '__main__':
    import unittest
    unittest.main()

