# Generated by Django 4.2.1 on 2023-08-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('lawyer', 'Lawyer'), ('student', 'Student'), ('client', 'Client')], default='client', max_length=10),
        ),
    ]
