# Generated by Django 4.2.4 on 2023-09-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_lawyerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
