# Generated by Django 4.2.4 on 2023-09-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_id_lawyerprofile_lawyer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawyerprofile',
            old_name='lawyer_id',
            new_name='id',
        ),
    ]
