# Generated by Django 4.2.4 on 2023-09-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('lawyer_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('min_cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('start_date', models.DateField()),
                ('duration', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('roles', models.TextField(help_text='Enter roles as bullet points (one per line)')),
            ],
        ),
    ]
