# Generated by Django 4.2.4 on 2023-09-02 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_internship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='lawyer_name',
        ),
        migrations.AddField(
            model_name='internship',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship',
            name='lawyer_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='accounts.lawyerprofile'),
            preserve_default=False,
        ),
    ]
