# Generated by Django 4.2.4 on 2023-09-03 09:41

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='specialization',
            field=models.CharField(choices=[('family ', 'Family Lawyer'), ('criminal ', 'Criminal Lawyer'), ('consumer ', 'Consumer Lawyer')], max_length=20),
        ),
    ]
