# Generated by Django 4.2.4 on 2023-09-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_certificate_lawyerprofile_bar_enrollment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='internship_images/'),
        ),
    ]
