# Generated by Django 4.2.4 on 2023-09-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_customuser_address_alter_customuser_adharno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='bar_enrollment_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='experience',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('family', 'Family Lawyer'), ('criminal', 'Criminal Lawyer'), ('consumer', 'Consumer Lawyer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
