# Generated by Django 4.2.4 on 2023-09-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_lawyerprofile_bar_enrollment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='adharno',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
