# Generated by Django 4.2.4 on 2023-09-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_customuser_adharno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='adharno',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
