# Generated by Django 4.2.4 on 2023-09-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_customuser_adharno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
