# Generated by Django 4.2.4 on 2023-09-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_lawyerprofile_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='license_no',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
