# Generated by Django 4.2.4 on 2023-09-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_lawyerprofile_license_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='adharno',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
