# Generated by Django 4.2.4 on 2023-09-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_customuser_adharno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='adharno',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
