# Generated by Django 4.2.4 on 2023-09-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_customuser_adharno_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='bar_enrollment_number',
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='working_days',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='working_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='working_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
