# Generated by Django 4.2.4 on 2023-09-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_lawyerprofile_bar_enrollment_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='working_days',
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='working_days',
            field=models.ManyToManyField(blank=True, to='accounts.day'),
        ),
    ]
