# Generated by Django 4.2.4 on 2023-09-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_lawyerprofile_working_time_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='end_time',
        ),
    ]
