# Generated by Django 4.2.4 on 2023-09-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_remove_timeslot_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='original_booking_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
