# Generated by Django 4.2.4 on 2023-09-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_booking_original_booking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerDayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.lawyerprofile')),
            ],
        ),
    ]
