# Generated by Django 4.2.4 on 2023-09-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_timeslot_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='name',
        ),
    ]
