# Generated by Django 4.2.4 on 2023-09-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_remove_timeslot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='name',
            field=models.CharField(default=11, max_length=30),
            preserve_default=False,
        ),
    ]
