# Generated by Django 4.2.4 on 2023-09-11 18:59

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('accounts', '0047_remove_timeslot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='locations',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
