# Generated by Django 4.2.4 on 2023-09-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_lawyerprofile_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='budget',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='cases_lost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='cases_won',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
