# Generated by Django 4.2.4 on 2023-09-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_lawyerprofile_budget_lawyerprofile_cases_lost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='cases_lost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
