# Generated by Django 4.2.4 on 2023-09-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_remove_lawyerprofile_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='court',
            field=models.CharField(blank=True, choices=[('jfcmcchangancherry', 'Judicial First Class Magistrate Court  Changancherry'), ('munsiff', 'Munsiff Court Changancherry'), ('jfcmcKanjirapally', 'Judicial First Class Magistrate Court  Kanjirapally'), ('munsifcourtkanjirapally', 'Munsiff Court Kanjirapally'), ('districtcourtkottayam', 'District Court Kottayam'), ('highcourtkochi', 'High Court Kochi')], max_length=200),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='uploads/default_profile_picture.png', null=True, upload_to='uploads/'),
        ),
    ]
