# Generated by Django 4.2.4 on 2023-09-14 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_holidayrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=10, unique=True)),
                ('client_name', models.CharField(blank=True, max_length=100)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=15)),
                ('incident_place', models.CharField(max_length=100)),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField()),
                ('witness_name', models.CharField(blank=True, max_length=100)),
                ('witness_details', models.TextField(blank=True)),
                ('incident_description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='accounts.lawyerprofile')),
            ],
        ),
    ]
