# Generated by Django 4.2.4 on 2023-09-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='client_adhar',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='client_adhar_photo',
            field=models.ImageField(blank=True, null=True, upload_to='aadhar_photos/'),
        ),
    ]
