# Generated by Django 4.2.4 on 2023-09-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_case_client_adhar_case_client_adhar_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=10)),
                ('client_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phnno', models.CharField(max_length=15)),
                ('incident_description', models.TextField()),
            ],
        ),
    ]
