# Generated by Django 4.2.4 on 2023-09-14 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_currentcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentcase',
            name='lawyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='current_cases', to='accounts.lawyerprofile'),
            preserve_default=False,
        ),
    ]
