# Generated by Django 4.2.4 on 2023-09-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_currentcase_lawyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/img/lawyers/1.png', null=True, upload_to='uploads/'),
        ),
    ]
