# Generated by Django 4.2.4 on 2023-09-17 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_alter_lawyerprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentcase',
            name='incident_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currentcase',
            name='incident_place',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currentcase',
            name='incident_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currentcase',
            name='witness_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='currentcase',
            name='witness_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
