# Generated by Django 4.2.4 on 2023-09-17 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_currentcase_incident_date_currentcase_incident_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='working_hours',
            field=models.ManyToManyField(blank=True, to='accounts.timeslot'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='main_slot',
            field=models.CharField(choices=[('8-10', '8:00 AM - 10:00 AM'), ('10-12', '10:00 AM - 12:00 PM'), ('1-3', '1:00 PM - 3:00 PM'), ('3-5', '3:00 PM - 5:00 PM')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('day', 'main_slot')},
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='start_time',
        ),
    ]
