# Generated by Django 4.2.4 on 2023-09-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_lawyerprofile_working_hours_timeslot_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='lawyers',
            field=models.ManyToManyField(blank=True, related_name='working_slots', to='accounts.lawyerprofile'),
        ),
    ]
