# Generated by Django 4.2.4 on 2023-09-17 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_appointment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('day', 'start_time', 'end_time')},
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='main_slot',
        ),
    ]
