# Generated by Django 4.2.4 on 2023-09-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='not_paid', max_length=20),
        ),
    ]
