# Generated by Django 4.2.4 on 2023-09-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_order_id',
            field=models.CharField(default=1, max_length=40, verbose_name='Order ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_id',
            field=models.CharField(default=1, max_length=36, verbose_name='Payment ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='signature_id',
            field=models.CharField(default=1, max_length=128, verbose_name='Signature ID'),
            preserve_default=False,
        ),
    ]
