# Generated by Django 4.2.4 on 2023-09-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='time_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
