# Generated by Django 4.2.4 on 2023-09-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_lawyerprofile_time_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='college',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_cgpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='student',
            name='adhaar_no',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='adhaar_pic',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='course_place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='duration_of_course',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='specialization',
            field=models.CharField(blank=True, choices=[('family', 'Family Lawyer'), ('criminal', 'Criminal Lawyer'), ('consumer', 'Consumer Lawyer'), ('corporate', 'Corporate Lawyer'), ('civilrights', 'Civil Rights Lawyer'), ('divorce', 'Divorce Lawyer')], max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='year_of_pass',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
