# Generated by Django 4.2.4 on 2023-09-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_remove_student_college_remove_student_current_cgpa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='adhaar_pic',
            field=models.ImageField(blank=True, null=True, upload_to='student_uploads/'),
        ),
    ]
