# Generated by Django 4.2.4 on 2023-09-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_appointment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialization',
            field=models.CharField(blank=True, choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_pass',
            field=models.CharField(blank=True, choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027')], max_length=50, null=True),
        ),
    ]
