# Generated by Django 4.2.4 on 2023-09-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0081_alter_student_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
