# Generated by Django 4.2.4 on 2023-09-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0083_remove_appointment_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='provider_order_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='signature_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
