# Generated by Django 4.2.4 on 2023-10-01 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0089_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.workassignment'),
        ),
    ]
