# Generated by Django 4.2.1 on 2023-10-22 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0092_remove_task_case_task_work_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='razorpay_signature',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.AlterField(
            model_name='student',
            name='specialization',
            field=models.CharField(blank=True, choices=[('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_pass',
            field=models.CharField(blank=True, choices=[('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_paid', 'Not Paid'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='not_paid', max_length=20)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.appointment')),
            ],
        ),
    ]
