# Generated by Django 4.2.1 on 2024-01-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0094_alter_application_id_alter_appointment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='additional_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
