# Generated by Django 4.2.6 on 2023-10-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0094_alter_application_id_alter_appointment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='lawyer',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='ContactEntry',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
