# Generated by Django 4.2.1 on 2024-01-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0095_lawyerprofile_additional_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.TextField(),
        ),
    ]
