# Generated by Django 4.2.1 on 2024-01-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0096_alter_task_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayrequest',
            name='reason',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holidayrequest',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='supporting_documents/'),
        ),
        migrations.AddField(
            model_name='holidayrequest',
            name='type',
            field=models.CharField(choices=[('dutyleave', 'Duty Leave'), ('casual_leave', 'Casual Leave')], default='vacation', max_length=20),
        ),
    ]
