# Generated by Django 4.2.1 on 2024-01-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0097_holidayrequest_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayrequest',
            name='timing',
            field=models.CharField(choices=[('full_day', 'Full Day'), ('half_day', 'Half Day')], default='full_day', max_length=10),
        ),
    ]
