# Generated by Django 5.0.1 on 2024-01-17 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0096_contactentry_booking'),
        ('accounts', '0099_lawyerprofile_additional_qualification_documents_and_more'),
    ]

    operations = [
    ]
