# Generated by Django 4.2.1 on 2024-02-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0099_lawyerprofile_additional_qualification_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='specialization',
            field=models.CharField(blank=True, choices=[('family', 'Family Lawyer'), ('criminal', 'Criminal Lawyer'), ('consumer', 'Consumer Lawyer'), ('corporate', 'Corporate Lawyer'), ('civilrights', 'Civil Rights Lawyer'), ('divorce', 'Divorce Lawyer')], max_length=50, null=True),
        ),
    ]
