# Generated by Django 4.2.1 on 2024-02-04 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0101_studentpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpayment',
            name='amount',
        ),
    ]
