# Generated by Django 5.0.1 on 2024-02-05 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0100_merge_20240117_0546'),
        ('accounts', '0103_application_status'),
    ]

    operations = [
    ]
