# Generated by Django 4.2.1 on 2024-02-05 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0105_notification_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='work_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.workassignment'),
        ),
    ]
