# Generated by Django 4.2.1 on 2024-02-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0106_notification_work_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workassignment',
            name='charge_fine',
            field=models.BooleanField(default=False),
        ),
    ]
