# Generated by Django 4.2.1 on 2024-02-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0108_finepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetracking',
            name='amount',
            field=models.IntegerField(default=10),
        ),
    ]
