# Generated by Django 4.2.1 on 2024-03-01 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0110_trackerpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casetracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.casetracking')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.lawyerprofile')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.trackerpayment')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.lawyerprofile')),
            ],
        ),
    ]
