# Generated by Django 4.2.1 on 2024-03-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0113_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sentiment_score',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
    ]
