# Generated by Django 4.2.1 on 2024-03-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0114_feedback_sentiment_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='sentiment_score',
            new_name='threshold',
        ),
    ]
