# Generated by Django 4.2.1 on 2024-03-09 13:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0115_rename_sentiment_score_feedback_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
