# Generated by Django 4.2.1 on 2024-03-09 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0117_alter_appointment_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer', to='accounts.lawyerprofile'),
        ),
    ]
