# Generated by Django 4.2.1 on 2024-03-28 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0118_alter_appointment_lawyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='lawyer',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='ContactEntry',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
